language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
    - composer install -o

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)
