language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)
