language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
    - composer install -o

before_script: phpenv config-add myphp.ini

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)
